version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/shopping-list
      - PORT=3000
      - SESSION_SECRET=your-secret-key-here
      - NODE_ENV=development
      - EMAIL_ADDRESS=your-email@gmail.com
      - EMAIL_PASSWORD=your-app-specific-password
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:4.4
    container_name: family_shopping_list_mongo_1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongodb_data:
